### ISSUE TITLE
Import `makeStyles` from core in useStyles transform

### ISSUE THREAD

**Issue by ljvanschie** [codemodsquad/material-ui-codemorphs#2]
Thanks for the great work! I use the VS Code extension quite a lot.

One request.. could we make the `useStyles` transform import `makeStyles` from `@material-ui/core` instead of `@material-ui/core/styles`, or make it configurable just like the `themeImport` setting?

**Comment by jedwards1211** [comment]
Thanks!  Yup, will do

**Comment by jedwards1211** [comment]
Okay, I made it where you can add `makeStylesImport` and `withStylesImport` options to your `package.json`, just like the `themeImport` setting 👍 
Will update the VSCode extension in a sec

**Comment by jedwards1211** [comment]
Okay, this is release in version 1.4.0 of the VSCode extension.  Cheers!

**Comment by ljvanschie** [comment]
Awesome, thanks a lot! 🎉

**Comment by jedwards1211** [comment]
Btw I just added a similar option to [Material-UI Snippets](https://github.com/vscodeshift/material-ui-snippets) if you're interested
